$ANSIBLE_VAULT;1.2;AES256;stg
61333265306334353031373433623038373233633431363363633835383565666264383533613133
3562663264373036313430336338303332336538393261660a646162373631653466303365623138
62653639333732613663363135643532636164656538356661363361313363393532346563306131
3835346265656233300a323832376634303739383935326433393061333665666264633233343035
63616361326561613263653465373733653633633435316230323462663832363866313534393837
33636665393866623739636664613132623162353361363034613334663136656166363764333731
376161353165306664363238346338656231
