$ANSIBLE_VAULT;1.1;AES256;prod
65356564343630666337646331383431303339616230323932303564383634613233613535363533
3162666530343835646130643362343766373361336531630a623262353761653035376136343961
30643438666663663463363831383531323763323965393435353037653963383831643066626630
6535326332626263620a363232356162333339386134396561363064303431373135343234333432
38663834626237346532623033646538313962383338366331333666323334626139613137316232
62653134663530316133343963613333303064313762323766383435373139323932313134623336
616463396663363230303366353538653036
